export const ERROR_CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  DEMO_FORBIDDEN: 'DEMO_FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  STALE_REVISION: 'STALE_REVISION',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  TRANSLATION_MISSING: 'TRANSLATION_MISSING',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
